SEP-6: Accept financial information via PATCH
stellar/stellar-protocol pull request #1380
Opened 2023-08-15 20:26 UTC by philipliu

2023-08-17 15:45 UTC, philipliu commented
I'm skipping a version here as I assume that the deposit PR will be merged first.

2023-08-17 16:14 UTC, JakeUrban requested changes
I definitely agree with the outcome we're trying to achieve here, but I think we should encourage clients to provide financial account data via SEP-12's `PUT /customer` requests, rather than SEP-6's `PATCH /transaction` request.

I think this simplifies client implementations (and the design of the anchor platform) because we don't have to support `PATCH /transaction` or the `pending_transaction_info_update` status. What do you think?

2023-08-17 16:34 UTC, philipliu commented
The challenge with using SEP-12 for accepting financial account information is when a user wants to use two different bank accounts (or two accounts of the same type) between withdrawals.

Let's suppose a user requests a withdrawal to the first bank account. Then, they submit another withdrawal request to another bank account. I see two ways of doing this:

1. Associate a set of bank account fields per transaction. Something like `bank_account_number.e0045691-23a7-4f9e-8c56-aeaf3a78010e`, for each transaction. When the transaction completes, we would need to delete these bank account fields. SEP-12 does not currently support deleting a subset of fields for a customer.
2. Block the second withdrawal until the first completes, then ask the user to submit new bank account information again using SEP-12. This would not allow for a user not to have concurrent withdrawals.

I think multi-account withdrawals are a use case we want to support. SEP-12 does not look like it's designed for ephemeral/transaction-related data, so using it would require us to design a partial delete API. I agree that using `/PATCH` is not ideal, but I feel like it's a simpler approach.

2023-08-17 16:55 UTC, philipliu commented
`/PATCH transaction` would only update the bank details for a single transaction.

The second withdrawal request would be moved into `pending_transaction_info_update` and the customer would be asked to provide bank details again using `PATCH /transaction`.

2023-08-17 17:10 UTC, JakeUrban commented
If the business doesn't store bank details of their customers for future transactions, then that puts responsibility on the wallet to do so, otherwise wallets will need to ask their users for the their bank account info on each transaction. And I don't know if it makes sense to have wallets store customer bank details, especially noncustodial wallets.

Whiles its not ideal, the existing approach of having at most 1 account per type on file works and ensures that customers only have to provide their bank details once. If customers want to use a different bank account, they can update their account on file with the anchor, and the wallet can decide how to build the UX for that. But I'd rather not try to solve a problem a small percentage of customers will use at the expense of additional complexity for wallets or a worse UX for the majority of customers who just use one off-chain account.

2023-08-17 17:19 UTC, philipliu commented
Thanks, @JakeUrban, that makes sense. I'll make the changes then.

2023-08-17 17:59 UTC, JakeUrban submitted a review, later dismissed

2023-08-17 18:19 UTC, Ifropc commented on ecosystem/sep-0006.md
> +* `types`: a field with each type of withdrawal supported for that asset as a key. Each type can specify a `fields` object as below explaining what fields are needed and what they do. Anchors are enc
Can you update Basic Wallet Implementation section to reflect this change?

2023-08-30 19:25 UTC, JakeUrban approved these changes

2023-08-30 19:52 UTC, JakeUrban approved these changes

2023-08-30 19:56 UTC, merged