SEP-24: deprecated postMessage callbacks
stellar/stellar-protocol pull request #870
Opened 2021-02-17 01:04 UTC by JakeUrban

Deprecates the use of `postMessage` callbacks.

Question: Do we want to deprecate the `callback` parameter altogether? `callback` is used for when the interactive flow has completed. But now that it is the anchor's responsibility to close the popup, I can't think of a reason why `callback` is valuable. `on_change_callback` can be used for all status changes, so the wallet could get an update when the transaction moves to `pending_user_transfer_start`.

2021-02-23 16:50 UTC, tomerweller requested changes
I think we need to add a more explicit deprecation notice that instructs wallets and anchors what to do. For example: if I'm an anchor receiving a `postMessage` callback parameter - what's my expected behavior? If I'm a wallet - what's my alternative?

2021-02-23 16:52 UTC, tomerweller commented
I agree that the existence of both `callback` and `on_change_callback` looks pretty vestigial. @JakeUrban can you open a different issue for that? No need to overload this pr

2021-02-23 18:10 UTC, JakeUrban commented
> @JakeUrban can you open a different issue for that?

I'll can open the PR when this is merged 👍

2021-02-24 18:39 UTC, tomerweller reviewed
lgtm

2021-02-24 18:40 UTC, tomerweller approved these changes

2021-02-24 18:49 UTC, merged