Updating SEP-12 title for clarity and usability
stellar/stellar-protocol pull request #923
Opened 2021-04-28 04:29 UTC by lydiat

**Context**
As part of an ongoing effort to improve the usability of our protocols, in Q1 of 2021 SDF held an internal review of several SEP titles with the goal of choosing usable, descriptive names. 

Our protocols have developed over many years and as they and the ecosystem have grown, the names that they were originally given have sometimes become less meaningful. We’ve found ourselves often referring to a protocol by its number instead of its title, which can be confusing for new members as it abstracts the meaning of the SEP in discussion. While we’ll continue to use the SEP-# namespace in technical discussions and in order to maintain searchability, this step towards plain language names will hopefully encourage their usage in addition to the numeric shorthand.

**Before: Anchor/Client customer info transfer
After: KYC API**
KYC API is much easier to say than “Anchor/Client customer info transfer” and while it’s comprised solely of acronyms, they’re both widely understood in the financial development industry. 

Spelling out Know Your Customer (KYC) in the title was considered as an educational opportunity, but it was decided that this work could be done in the body of the protocol.

2021-04-29 02:34 UTC, leighmcculloch approved these changes

2021-05-19 16:24 UTC, JakeUrban requested changes
Title looks good, but can you update the meta info as well?

2021-05-20 03:31 UTC, lydiat reviewed
👍

2021-05-20 16:19 UTC, JakeUrban approved these changes

2021-05-20 17:04 UTC, merged